/*
 * Copyright 2025 Greta Modernization Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package greta.core.utilx.gui;

import greta.core.util.CharacterManager;
import greta.core.util.IniManager;
import greta.core.util.IniParameter;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;

/**
 *
 * @author Andre-Marie Pez
 */
public class CharacterInstanceFrame extends javax.swing.JFrame{

    private static HashMap<Integer,CharacterInstanceFrame> instances=new HashMap<>();
    private int ID;
    private String character=null;

    public static CharacterInstanceFrame get(int ID){
        if(instances.containsKey(ID))
            return instances.get(ID);
        else{
            System.err.println("No CharacterInstanceFrame instance found for: "+ID);
            return null;
        }
    }

    /**
     * Default constructor
     */
    public CharacterInstanceFrame(){
        initComponents();
        ID = instances.size();
        instances.put(ID, this);

        ArrayList<String>names = new ArrayList<>();
        for(IniParameter param :IniManager.getGlobals().getAll()){
            if((new File(param.getParamValue()).exists() && param.getParamValue().toLowerCase().endsWith(".ini"))){
                names.add(param.getParamName().toUpperCase());
            }
        }
        Collections.sort(names, String.CASE_INSENSITIVE_ORDER);
        javax.swing.DefaultComboBoxModel model = new javax.swing.DefaultComboBoxModel(names.toArray());
        jComboBox1.setModel(model);
        jComboBox1.addItemListener(new ItemListener(){
            @Override
            public void itemStateChanged(ItemEvent e) {
                if(e.getStateChange() == ItemEvent.SELECTED){
                    setCurrentCharacter(e.getItem().toString());
                }
            }
        });
        jComboBox1.setSelectedItem(CharacterManager.getStaticInstance().getCurrentCharacterName().toUpperCase());
    }

    public String getCurrentCharacter(){
        return character;
    }


    public void setCurrentCharacter(String name){
        if(name!=null && !name.isEmpty())
            character = name;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

       jComboBox1 = new javax.swing.JComboBox();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "greta" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();

    }// </editor-fold>

   // Variables declaration - do not modify
    private javax.swing.JComboBox jComboBox1;
    // End of variables declaration
}
