/*
 * This file is part of Greta.
 *
 * Greta is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Greta is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Greta.  If not, see <https://www.gnu.org/licenses/>.
 *
 */
package greta.core.utilx.gui;

import greta.core.util.IniManager;
import greta.core.util.IniParameter;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 *
 * @author Andre-Marie Pez
 */
public class IniManagerFrame extends javax.swing.JFrame {


    IniLoader characterIniLoader;
    IniLoader languageIniLoader;
    private IniManager iniManager = null;

    /** Creates new form IniManagerFrame */
    public IniManagerFrame() {
        initComponents();
        setLocale(Locale.getDefault());
    }

    public void connect(IniLoader CharacterIniLoader, IniLoader LanguageIniLoader){
        this.characterIniLoader = CharacterIniLoader;
        this.languageIniLoader = LanguageIniLoader;
        loaderContainer1.setViewportView(this.characterIniLoader);
        loaderContainer2.setViewportView(this.languageIniLoader);
        this.characterIniLoader.setManagerFrame(this);
        this.languageIniLoader.setManagerFrame(this);
    }

    public void connect(IniLoader CharacterIniLoader){
        this.characterIniLoader = CharacterIniLoader;
        loaderContainer1.setViewportView(this.characterIniLoader);
        this.characterIniLoader.setManagerFrame(this);
    }    
    
    public void setIniManager(IniManager iniManager){
        this.iniManager=iniManager;
        jTable1.getModel().addTableModelListener(new TableModelListener(){
            @Override
            public void tableChanged(TableModelEvent tme) {
                if(IniManagerFrame.this.iniManager == null) {
                    return;
                }
                if(TableModelEvent.UPDATE == tme.getType() && tme.getFirstRow()>=0){
                    String name = jTable1.getValueAt(tme.getFirstRow(), 0).toString();
                    String value = jTable1.getValueAt(tme.getFirstRow(), 1).toString();
                    IniManagerFrame.this.iniManager.setValueString(name, value);
                    IniManagerFrame.this.characterIniLoader.fireIniChanged();
                    IniManagerFrame.this.languageIniLoader.fireIniChanged();
                }
            }
        });
        List<IniParameter> params = iniManager.getAll();
        Collections.sort(params, new Comparator<IniParameter>() {

            @Override
            public int compare(IniParameter o1, IniParameter o2) {
                return String.CASE_INSENSITIVE_ORDER.compare(o1.getParamName(), o2.getParamName());
            }
        });
        for(IniParameter param : params){
            ((javax.swing.table.DefaultTableModel)jTable1.getModel()).addRow(new String[]{param.getParamName(),param.getParamValue()});
        }

    }

    public void setDefinition(String name){
        //here, empty definition are not permited
        if(name==null || name.isEmpty()){
            return ;
        }
        iniManager.setDefinition(name);
        updateIniParameters();
        characterIniLoader.fireIniDefinitionChanged(name);
    }

    public String getDefinition(){
        return iniManager.getCurrentDefinition().getName();
    }


    protected void updateIniParameters(){
        for(int i=0; i<jTable1.getRowCount(); ++i){
            jTable1.setValueAt(iniManager.getValueString(jTable1.getValueAt(i, 0).toString()), i, 1);
        }
    }

    @Override
    public void setLocale(Locale l) {
        super.setLocale(l);
        if(jTable1!=null) {
            ((javax.swing.table.DefaultTableModel)jTable1.getModel())
                    .setColumnIdentifiers(
                    new String[]{
                        IniManager.getLocaleProperty("word.parameter", l),
                        IniManager.getLocaleProperty("word.value", l)
                    });
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        loaderContainer1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loaderContainer2 = new javax.swing.JScrollPane();
        jSeparator1 = new javax.swing.JSeparator();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Parameter", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable1);

        loaderContainer1.setBorder(null);

        jLabel1.setText("Character");

        jLabel2.setText("Language");

        loaderContainer2.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loaderContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loaderContainer2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loaderContainer1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loaderContainer2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane loaderContainer1;
    private javax.swing.JScrollPane loaderContainer2;
    // End of variables declaration//GEN-END:variables

}
