/*
 * Copyright 2025 Greta Modernization Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package greta.core.utilx.gui;

import greta.core.util.CharacterManager;
import greta.core.util.speech.Speech;
import greta.core.util.speech.TTS;

/**
 *
 * @author Andre-Marie Pez
 */
public class NVBG_MM_Controller extends javax.swing.JFrame {

    private CharacterManager cm;

    /** Creates new form TTSController */
    public NVBG_MM_Controller(CharacterManager cm) {
        this.cm = cm;
        initComponents();
        doMM.setSelected(false);
        doNVBG.setSelected(false);
    }

    private void updateNVBG_MM_Options(){
            if(doNVBG.isSelected()){
                this.cm.set_use_NVBG(true); 
            }
            else{
                this.cm.set_use_NVBG(false); 
            }
            if(doMM.isSelected()){
                this.cm.set_use_MM(true);            
            }
            else{
                this.cm.set_use_MM(false); 
            }
            
            
    }


    public boolean getNVBG(){
        return doNVBG.isSelected();
    }


    public boolean getMM(){
        return doMM.isSelected();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doNVBG = new greta.core.utilx.gui.ToolBox.LocalizedJCheckBox("NVBG");
        doMM = new greta.core.utilx.gui.ToolBox.LocalizedJCheckBox("Meaning Miner");

        doNVBG.setSelected(true);
        doNVBG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doNVBGActionPerformed(evt);
            }
        });

        doMM.setSelected(true);
        doMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doMMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doNVBG)
                    .addComponent(doMM))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(doNVBG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(doMM)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doNVBGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doNVBGActionPerformed
        updateNVBG_MM_Options();
    }//GEN-LAST:event_doNVBGActionPerformed

    private void doMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doMMActionPerformed
        updateNVBG_MM_Options();
    }//GEN-LAST:event_doMMActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox doMM;
    private javax.swing.JCheckBox doNVBG;
    // End of variables declaration//GEN-END:variables

}
