/* This file is part of Greta.
 * Greta is free software: you can redistribute it and / or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* 
* Greta is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with Greta.If not, see <http://www.gnu.org/licenses/>.
*//*
 * This file is part of VIB (Virtual Interactive Behaviour).
 */
package vib.core.utilx.gui;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import vib.core.util.CharacterDependent;
import vib.core.util.CharacterManager;
import vib.core.util.IniManager;
import vib.core.util.IniParameter;
import vib.core.util.log.Logs;

/**
 *
 * @author Andre-Marie Pez
 */
public class CharacterIniLoader extends IniLoader implements CharacterDependent{

    /** Creates new form CharacterIniLoader */
    public CharacterIniLoader() {
        initComponents();

        ArrayList<String>names = new ArrayList<String>();
        for(IniParameter param :IniManager.getGlobals().getAll()){
            if((new File(param.getParamValue()).exists() && param.getParamValue().toLowerCase().endsWith(".ini"))){
                names.add(param.getParamName().toUpperCase());
            }
        }
        Collections.sort(names, String.CASE_INSENSITIVE_ORDER);
        javax.swing.DefaultComboBoxModel model = new javax.swing.DefaultComboBoxModel(names.toArray());
        jComboBox1.setModel(model);
        jComboBox1.addItemListener(new ItemListener(){
            @Override
            public void itemStateChanged(ItemEvent e) {
                if(e.getStateChange() == ItemEvent.SELECTED){
                    CharacterManager.setCharacter(e.getItem().toString());
                }
            }
        });
        jComboBox1.setSelectedItem(CharacterManager.getCurrentCharacterName().toUpperCase());
        CharacterManager.add(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "greta" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, 0, 56, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onCharacterChanged() {
        jComboBox1.setSelectedItem(CharacterManager.getCurrentCharacterName().toUpperCase());
        Logs.info("Current character parameters changed.");
        IniManager.getGlobals().get("CURRENT_CHARACTER").setParamValue(CharacterManager.getCurrentCharacterName().toUpperCase());
        fire = false;
        managerFrame.updateIniParameters();
        fire = true;
    }

    private boolean fire = true;
    @Override
    public void fireIniChanged() {
        if(fire){
            CharacterManager.notifyChanges();
        }
    }

    @Override
    public void fireIniDefinitionChanged(String name) {}
    
}
