/* This file is part of Greta.
 * Greta is free software: you can redistribute it and / or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* 
* Greta is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with Greta.If not, see <http://www.gnu.org/licenses/>.
*//*
 * This file is part of VIB (Virtual Interactive Behaviour).
 */
package vib.core.utilx.gui;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import vib.core.util.CharacterManager;
import vib.core.util.IniManager;
import vib.core.util.IniParameter;
import vib.core.behaviorrealizer.Realizer;


/**
 *
 * @author Andre-Marie Pez
 */
public class CharacterInstanceFrame extends javax.swing.JFrame{
    
    private static HashMap<Integer,CharacterInstanceFrame> instances=new HashMap<>();
    private int ID;
    private String character=null;
    private Realizer realizer;
    
    public static CharacterInstanceFrame get(int ID){
        if(instances.containsKey(ID))
            return instances.get(ID);
        else{            
            System.err.println("No CharacterInstanceFrame instance found for: "+ID);
            return null;
        }
    }
    
    /*
    * UI link methods    
    */
    public void setCharacter(Realizer realizer){
        this.realizer = realizer;
       
    }
    public void unsetCharacter(Realizer realizer){
        realizer = null;
    }
    
    
    /**
     * Default constructor
     */
    public CharacterInstanceFrame(){
        initComponents();
        ID = instances.size();
        instances.put(ID, this);
        
        ArrayList<String>names = new ArrayList<>();
        for(IniParameter param :IniManager.getGlobals().getAll()){
            if((new File(param.getParamValue()).exists() && param.getParamValue().toLowerCase().endsWith(".ini"))){
                names.add(param.getParamName().toUpperCase());
            }
        }
        Collections.sort(names, String.CASE_INSENSITIVE_ORDER);
        javax.swing.DefaultComboBoxModel model = new javax.swing.DefaultComboBoxModel(names.toArray());
        jComboBox1.setModel(model);
        jComboBox1.addItemListener(new ItemListener(){
            @Override
            public void itemStateChanged(ItemEvent e) {
                if(e.getStateChange() == ItemEvent.SELECTED){
                    setCurrentCharacter(e.getItem().toString());
                }
            }
        });
        jComboBox1.setSelectedItem(CharacterManager.getStaticInstance().getCurrentCharacterName().toUpperCase());
    }

    public String getCurrentCharacter(){
        return character;
    }
    

    public void setCurrentCharacter(String name){
        if(name!=null && !name.isEmpty())
            character = name;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        
       jComboBox1 = new javax.swing.JComboBox();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "greta" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        
    }// </editor-fold>                        

   // Variables declaration - do not modify                     
    private javax.swing.JComboBox jComboBox1;
    // End of variables declaration                   
}
