/*
 * Copyright 2025 Greta Modernization Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package greta.auxiliary.ssi;

import java.util.Arrays;
import java.util.stream.Collectors;

/**
 *
 * @author Angelo Cafaro
 */
public class SSIFilterForm extends javax.swing.JFrame {

    private SSIXMLToFrameTranslator ssiTranslator;

    /**
     * Creates new form SSIFilterForm
     */
    public SSIFilterForm() {
        initComponents();

        // get the 'friendly' names for the filter options
        String[] names = Arrays.asList(SSIXMLToFrameTranslator.SSIParsingFilterOption.values())
                .stream()
                .map(SSIXMLToFrameTranslator.SSIParsingFilterOption::toString)
                .collect(Collectors.toList())
                .toArray(new String[SSIXMLToFrameTranslator.SSIParsingFilterOption.size]);

        // set the values straight from the filter options,
        ssiFilterFormChoice.setModel(new javax.swing.DefaultComboBoxModel<>(names));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ssiFilterFormChoice = new javax.swing.JComboBox();
        ssiFilterFormLbl = new javax.swing.JLabel();

        ssiFilterFormChoice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Prosody Only", "Head Only", "Body Only" }));
        ssiFilterFormChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssiFilterFormChoiceActionPerformed(evt);
            }
        });

        ssiFilterFormLbl.setText("Parse: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ssiFilterFormLbl)
                .addGap(18, 18, 18)
                .addComponent(ssiFilterFormChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssiFilterFormLbl)
                    .addComponent(ssiFilterFormChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ssiFilterFormChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssiFilterFormChoiceActionPerformed
        if (ssiTranslator != null) {
            int index = ssiFilterFormChoice.getSelectedIndex();
            if (index >= 0)
            {
                ssiTranslator.SetParserFilter(index);
            }
        }
    }//GEN-LAST:event_ssiFilterFormChoiceActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ssiFilterFormChoice;
    private javax.swing.JLabel ssiFilterFormLbl;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the ssiTranslator
     */
    public SSIXMLToFrameTranslator getSSITranslator() {
        return ssiTranslator;
    }

    /**
     * @param ssiTranslator the ssiTranslator to set
     */
    public void setSSITranslator(SSIXMLToFrameTranslator ssiTranslator) {
        this.ssiTranslator = ssiTranslator;
    }

}
