/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vib_auxiliary_player_ogre_natives_Bone */

#ifndef _Included_vib_auxiliary_player_ogre_natives_Bone
#define _Included_vib_auxiliary_player_ogre_natives_Bone
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vib_auxiliary_player_ogre_natives_Bone
 * Method:    __update
 * Signature: (JZZ)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_Bone__1_1update
  (JNIEnv *, jobject, jlong, jboolean, jboolean);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Bone
 * Method:    _getPosition
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_Bone__1getPosition
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Bone
 * Method:    __getDerivedOrientation
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_Bone__1_1getDerivedOrientation
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Bone
 * Method:    _getOrientation
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_Bone__1getOrientation
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Bone
 * Method:    _setOrientation
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_Bone__1setOrientation__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Bone
 * Method:    _setOrientation
 * Signature: (JDDDD)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_Bone__1setOrientation__JDDDD
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Bone
 * Method:    _setManuallyControlled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_Bone__1setManuallyControlled
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Bone
 * Method:    _setPosition
 * Signature: (JDDD)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_Bone__1setPosition
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Bone
 * Method:    _setScale
 * Signature: (JDDD)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_Bone__1setScale
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Bone
 * Method:    _getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_vib_auxiliary_player_ogre_natives_Bone__1getName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Bone
 * Method:    _numChildren
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_vib_auxiliary_player_ogre_natives_Bone__1numChildren
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Bone
 * Method:    _getChild_getName
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_vib_auxiliary_player_ogre_natives_Bone__1getChild_1getName
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Bone
 * Method:    __getDerivedPosition
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_Bone__1_1getDerivedPosition
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Bone
 * Method:    _getParent
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_Bone__1getParent
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Bone
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_Bone_delete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
