/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vib_auxiliary_player_ogre_natives_GpuProgramParameters */

#ifndef _Included_vib_auxiliary_player_ogre_natives_GpuProgramParameters
#define _Included_vib_auxiliary_player_ogre_natives_GpuProgramParameters
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vib_auxiliary_player_ogre_natives_GpuProgramParameters
 * Method:    _setNamedConstant_int_star
 * Signature: (JLjava/lang/String;JII)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_GpuProgramParameters__1setNamedConstant_1int_1star
  (JNIEnv *, jobject, jlong, jstring, jlong, jint, jint);

/*
 * Class:     vib_auxiliary_player_ogre_natives_GpuProgramParameters
 * Method:    _setNamedConstant_float_star
 * Signature: (JLjava/lang/String;JII)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_GpuProgramParameters__1setNamedConstant_1float_1star
  (JNIEnv *, jobject, jlong, jstring, jlong, jint, jint);

/*
 * Class:     vib_auxiliary_player_ogre_natives_GpuProgramParameters
 * Method:    _setNamedConstant
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_GpuProgramParameters__1setNamedConstant
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     vib_auxiliary_player_ogre_natives_GpuProgramParameters
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_GpuProgramParameters_delete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
