/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vib_auxiliary_player_ogre_natives_LogManager */

#ifndef _Included_vib_auxiliary_player_ogre_natives_LogManager
#define _Included_vib_auxiliary_player_ogre_natives_LogManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vib_auxiliary_player_ogre_natives_LogManager
 * Method:    set_LL_BOREME
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_LogManager_set_1LL_1BOREME
  (JNIEnv *, jclass);

/*
 * Class:     vib_auxiliary_player_ogre_natives_LogManager
 * Method:    set_LL_LOW
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_LogManager_set_1LL_1LOW
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
