/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vib_auxiliary_player_ogre_natives_Quaternion */

#ifndef _Included_vib_auxiliary_player_ogre_natives_Quaternion
#define _Included_vib_auxiliary_player_ogre_natives_Quaternion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vib_auxiliary_player_ogre_natives_Quaternion
 * Method:    _getIDENTITY
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_Quaternion__1getIDENTITY
  (JNIEnv *, jclass);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Quaternion
 * Method:    _instanciate
 * Signature: (DDDD)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_Quaternion__1instanciate__DDDD
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Quaternion
 * Method:    _instanciate
 * Signature: (DJ)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_Quaternion__1instanciate__DJ
  (JNIEnv *, jclass, jdouble, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Quaternion
 * Method:    _getw
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_vib_auxiliary_player_ogre_natives_Quaternion__1getw
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Quaternion
 * Method:    _getx
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_vib_auxiliary_player_ogre_natives_Quaternion__1getx
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Quaternion
 * Method:    _gety
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_vib_auxiliary_player_ogre_natives_Quaternion__1gety
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Quaternion
 * Method:    _getz
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_vib_auxiliary_player_ogre_natives_Quaternion__1getz
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Quaternion
 * Method:    _getPitch
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_vib_auxiliary_player_ogre_natives_Quaternion__1getPitch
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Quaternion
 * Method:    _getYaw
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_vib_auxiliary_player_ogre_natives_Quaternion__1getYaw
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Quaternion
 * Method:    _getRoll
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_vib_auxiliary_player_ogre_natives_Quaternion__1getRoll
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Quaternion
 * Method:    _Inverse
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_Quaternion__1Inverse
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Quaternion
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_Quaternion_delete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
