/*
 * This file is part of the auxiliaries of Greta.
 *
 * Greta is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Greta is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Greta.  If not, see <https://www.gnu.org/licenses/>.
 *
 */
package greta.auxiliary.conversationalGaze.Gui;

import greta.auxiliary.conversationalGaze.AgentGazeUser;
import greta.core.util.time.Timer;

/**
 *
 * @author Donatella Simonetti
 */
public class SetCamPos extends javax.swing.JFrame {

    AgentGazeUser gazeuser;
    private Thread statusgazeDisplay;
    private static final long SLEEP_TIME = 50; //miliiseconds
    /**
     * Creates new form GazeUserGui
     */
    public SetCamPos() {
        initComponents();

        statusgazeDisplay = new Thread(new Runnable() {
            @Override
            public void run() {
                while(true){
                    agentgazestatus.setText(Integer.toString(gazeuser.getStatus_AU()[0]));
                    usergazestatus.setText(Integer.toString(gazeuser.getStatus_AU()[1]));
                    voiceEnergy.setText(Double.toString(gazeuser.getVoiceEnergy()));
                    Timer.sleep(SLEEP_TIME);
                }
            }
        });
        statusgazeDisplay.setDaemon(true);
        statusgazeDisplay.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new java.awt.Canvas();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        agent_MG = new javax.swing.JTextField();
        agent_LA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        label_mg_au = new javax.swing.JLabel();
        label_la_au = new javax.swing.JLabel();
        AU_mutualGaze = new javax.swing.JTextField();
        AU_lookAway = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 32767));
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        agentgazestatus = new javax.swing.JTextField();
        usergazestatus = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        voiceEnergy = new javax.swing.JTextField();
        thresholdIsSpeaking = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jLabel1.setText("Agent");

        jLabel2.setText("Time Mutual Gaze (ms)");

        jLabel3.setText("Time Look Away (ms)");

        agent_MG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agent_MGActionPerformed(evt);
            }
        });

        agent_LA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agent_LAActionPerformed(evt);
            }
        });

        jLabel5.setText("Agent - User");

        label_mg_au.setText("Time Mutual Gaze (ms)");

        label_la_au.setText("Time Look Away (ms)");

        AU_mutualGaze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AU_mutualGazeActionPerformed(evt);
            }
        });

        AU_lookAway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AU_lookAwayActionPerformed(evt);
            }
        });

        jSeparator2.setMaximumSize(new java.awt.Dimension(50, 10));

        jSeparator3.setMaximumSize(new java.awt.Dimension(50, 10));

        agentgazestatus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        agentgazestatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentgazestatusActionPerformed(evt);
            }
        });

        usergazestatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usergazestatusActionPerformed(evt);
            }
        });

        jLabel6.setText("Gaze Status");

        jLabel7.setText("Agent");

        jLabel8.setText("User");

        jLabel9.setText("User Voice");

        voiceEnergy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voiceEnergyActionPerformed(evt);
            }
        });

        thresholdIsSpeaking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thresholdIsSpeakingActionPerformed(evt);
            }
        });

        jLabel10.setText("Intensity");

        jLabel11.setText("Threshold");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(agent_MG, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(agent_LA, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel8)
                                .addGap(16, 16, 16))
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(agentgazestatus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(usergazestatus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(33, 33, 33))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_mg_au)
                                    .addComponent(label_la_au))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(AU_mutualGaze, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AU_lookAway, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(4, 4, 4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(thresholdIsSpeaking, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(voiceEnergy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(38, 38, 38)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel3)
                                    .addComponent(agent_LA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                            .addComponent(jLabel2)
                                            .addComponent(agent_MG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(agentgazestatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(usergazestatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel5))
                            .addComponent(jLabel9))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator5)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(AU_mutualGaze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_mg_au)
                            .addComponent(voiceEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(label_la_au)
                            .addComponent(AU_lookAway, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thresholdIsSpeaking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agent_MGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agent_MGActionPerformed
        if (agent_MG.getText()!= null){
            synchronized(agent_MG){
                this.gazeuser.getAgent().setTime_MG(Double.parseDouble(agent_MG.getText()));
            }

        }
    }//GEN-LAST:event_agent_MGActionPerformed

    private void agent_LAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agent_LAActionPerformed
        if (agent_LA.getText()!= null){
            synchronized(agent_LA){
                this.gazeuser.getAgent().setTime_MG(Double.parseDouble(agent_LA.getText()));
            }

        }
    }//GEN-LAST:event_agent_LAActionPerformed

    private void AU_mutualGazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AU_mutualGazeActionPerformed
       if (AU_mutualGaze.getText()!= null){
            synchronized(AU_mutualGaze){
                this.gazeuser.setT_bothMG(Double.parseDouble(AU_mutualGaze.getText()));
            }

        }
    }//GEN-LAST:event_AU_mutualGazeActionPerformed

    private void AU_lookAwayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AU_lookAwayActionPerformed
        if (AU_lookAway.getText()!= null){
            synchronized(AU_lookAway){
                this.gazeuser.setT_bothAway(Double.parseDouble(AU_lookAway.getText()));
            }

        }
    }//GEN-LAST:event_AU_lookAwayActionPerformed

    private void agentgazestatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentgazestatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agentgazestatusActionPerformed

    private void usergazestatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usergazestatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usergazestatusActionPerformed

    private void voiceEnergyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voiceEnergyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_voiceEnergyActionPerformed

    private void thresholdIsSpeakingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thresholdIsSpeakingActionPerformed
        if (thresholdIsSpeaking.getText()!= null){
            synchronized(thresholdIsSpeaking){
                this.gazeuser.setThreshouldIntensity(Double.parseDouble(thresholdIsSpeaking.getText()));
            }
        }
    }//GEN-LAST:event_thresholdIsSpeakingActionPerformed

    public void setPosandOrient (AgentGazeUser gazeuser){
        this.gazeuser = gazeuser;
        this.agent_LA.setText(Double.toString(this.gazeuser.getAgent().getTime_LA()));
        this.agent_MG.setText(Double.toString(this.gazeuser.getAgent().getTime_MG()));
        this.AU_lookAway.setText(Double.toString(this.gazeuser.getT_bothAway()));
        this.AU_mutualGaze.setText(Double.toString(this.gazeuser.getT_bothMG()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AU_lookAway;
    private javax.swing.JTextField AU_mutualGaze;
    private javax.swing.JTextField agent_LA;
    private javax.swing.JTextField agent_MG;
    private javax.swing.JTextField agentgazestatus;
    private javax.swing.Box.Filler filler1;
    private java.awt.Canvas image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel label_la_au;
    private javax.swing.JLabel label_mg_au;
    private javax.swing.JTextField thresholdIsSpeaking;
    private javax.swing.JTextField usergazestatus;
    private javax.swing.JTextField voiceEnergy;
    // End of variables declaration//GEN-END:variables

public double getMutualGaze(){
    return Double.parseDouble(agent_MG.getText());
}

public double getLookAway(){
    return Double.parseDouble(agent_LA.getText());
}

public double getAU_MG(){
    return Double.parseDouble(AU_mutualGaze.getText());
}

public double getAU_LA(){
    return Double.parseDouble(AU_lookAway.getText());
}

public void setAgentMG(double value){
    agent_MG.setText(Double.toString(value));
    gazeuser.getAgent().setTime_MG(value);
}

public void setAgentLA(double value){
    agent_LA.setText(Double.toString(value));
    gazeuser.getAgent().setTime_LA(value);
}

public void setAU_MG(double value){
    AU_mutualGaze.setText(Double.toString(value));
    gazeuser.setT_bothMG(value);
}

public void setAU_LA(double value){
    AU_lookAway.setText(Double.toString(value));
    gazeuser.setT_bothAway(value);
}

public void setThreshold(double value){
    thresholdIsSpeaking.setText(Double.toString(value));
    gazeuser.setThreshouldIntensity(value);
}

public double getThreshold(){
    return Double.parseDouble(thresholdIsSpeaking.getText());
}


}
