/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vib_auxiliary_player_ogre_natives_Animation */

#ifndef _Included_vib_auxiliary_player_ogre_natives_Animation
#define _Included_vib_auxiliary_player_ogre_natives_Animation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vib_auxiliary_player_ogre_natives_Animation
 * Method:    _createVertexTrack_VAT_POSE
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_Animation__1createVertexTrack_1VAT_1POSE
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Animation
 * Method:    _getVertexTrack
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_Animation__1getVertexTrack
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Animation
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_Animation_delete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
