/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vib_auxiliary_player_ogre_natives_MeshManager */

#ifndef _Included_vib_auxiliary_player_ogre_natives_MeshManager
#define _Included_vib_auxiliary_player_ogre_natives_MeshManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vib_auxiliary_player_ogre_natives_MeshManager
 * Method:    _load
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_MeshManager__1load
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     vib_auxiliary_player_ogre_natives_MeshManager
 * Method:    getBoundsPaddingFactor
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_vib_auxiliary_player_ogre_natives_MeshManager_getBoundsPaddingFactor
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
