/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vib_auxiliary_player_ogre_natives_Pass */

#ifndef _Included_vib_auxiliary_player_ogre_natives_Pass
#define _Included_vib_auxiliary_player_ogre_natives_Pass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vib_auxiliary_player_ogre_natives_Pass
 * Method:    _hasFragmentProgram
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_vib_auxiliary_player_ogre_natives_Pass__1hasFragmentProgram
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Pass
 * Method:    _getFragmentProgramParameters
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_Pass__1getFragmentProgramParameters
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Pass
 * Method:    _setAmbient
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_Pass__1setAmbient
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Pass
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_Pass_delete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
