/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vib_auxiliary_player_ogre_natives_SceneNode */

#ifndef _Included_vib_auxiliary_player_ogre_natives_SceneNode
#define _Included_vib_auxiliary_player_ogre_natives_SceneNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _yaw
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1yaw
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _pitch
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1pitch
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _roll
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1roll
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    __update
 * Signature: (JZZ)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1_1update
  (JNIEnv *, jobject, jlong, jboolean, jboolean);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    __getDerivedOrientation
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1_1getDerivedOrientation
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _setPosition
 * Signature: (JDDD)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1setPosition__JDDD
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _attachObject
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1attachObject
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _getOrientation
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1getOrientation
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _setVisible
 * Signature: (JZZ)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1setVisible
  (JNIEnv *, jobject, jlong, jboolean, jboolean);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _getParentSceneNode
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1getParentSceneNode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    __getDerivedPosition
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1_1getDerivedPosition
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _getScale
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1getScale
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _createChildSceneNode
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1createChildSceneNode__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _translate
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1translate
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _setOrientation
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1setOrientation
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _getPosition
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1getPosition
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _removeAllChildren
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1removeAllChildren
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _scale
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1scale
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _createChildSceneNode
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1createChildSceneNode__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _createChildSceneNode
 * Signature: (JLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1createChildSceneNode__JLjava_lang_String_2J
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _setScale
 * Signature: (JDDD)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1setScale__JDDD
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _setPosition
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1setPosition__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _setScale
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1setScale__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _removeChild
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1removeChild
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _addChild
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1addChild
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _getChild_getName
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1getChild_1getName
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _numChildren
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1numChildren
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1getName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _removeAndDestroyAllChildren
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1removeAndDestroyAllChildren
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _getAttachedObject
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1getAttachedObject
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    _numAttachedObjects
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode__1numAttachedObjects
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneNode
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_SceneNode_delete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
