/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vib_auxiliary_player_ogre_natives_SceneManager */

#ifndef _Included_vib_auxiliary_player_ogre_natives_SceneManager
#define _Included_vib_auxiliary_player_ogre_natives_SceneManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneManager
 * Method:    _createEntity_PT_SPHERE
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_SceneManager__1createEntity_1PT_1SPHERE
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneManager
 * Method:    _createEntity_PT_CUBE
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_SceneManager__1createEntity_1PT_1CUBE
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneManager
 * Method:    _destroyMovableObject
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_SceneManager__1destroyMovableObject
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneManager
 * Method:    _setFog_FOG_EXP
 * Signature: (JJDDD)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_SceneManager__1setFog_1FOG_1EXP
  (JNIEnv *, jobject, jlong, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneManager
 * Method:    _createRayQuery
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_SceneManager__1createRayQuery
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneManager
 * Method:    _getRootSceneNode
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_SceneManager__1getRootSceneNode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneManager
 * Method:    _createCamera
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_SceneManager__1createCamera
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneManager
 * Method:    _showBoundingBoxes
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_SceneManager__1showBoundingBoxes
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneManager
 * Method:    _createEntity
 * Signature: (JLjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_SceneManager__1createEntity
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneManager
 * Method:    _hasSceneNode
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_vib_auxiliary_player_ogre_natives_SceneManager__1hasSceneNode
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneManager
 * Method:    _getSceneNode
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_SceneManager__1getSceneNode
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneManager
 * Method:    _setAmbientLight
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_SceneManager__1setAmbientLight
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneManager
 * Method:    _hasEntity
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_vib_auxiliary_player_ogre_natives_SceneManager__1hasEntity
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneManager
 * Method:    _getEntity
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_SceneManager__1getEntity
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneManager
 * Method:    _createLight
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_SceneManager__1createLight
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneManager
 * Method:    _hasLight
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_vib_auxiliary_player_ogre_natives_SceneManager__1hasLight
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneManager
 * Method:    _getLight
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_SceneManager__1getLight
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     vib_auxiliary_player_ogre_natives_SceneManager
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_SceneManager_delete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class vib_auxiliary_player_ogre_natives_SceneManager_PrefabType */

#ifndef _Included_vib_auxiliary_player_ogre_natives_SceneManager_PrefabType
#define _Included_vib_auxiliary_player_ogre_natives_SceneManager_PrefabType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
