/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vib_auxiliary_player_ogre_natives_TextureManager */

#ifndef _Included_vib_auxiliary_player_ogre_natives_TextureManager
#define _Included_vib_auxiliary_player_ogre_natives_TextureManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vib_auxiliary_player_ogre_natives_TextureManager
 * Method:    _getSingleton
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_TextureManager__1getSingleton
  (JNIEnv *, jclass);

/*
 * Class:     vib_auxiliary_player_ogre_natives_TextureManager
 * Method:    _remove
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_TextureManager__1remove
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     vib_auxiliary_player_ogre_natives_TextureManager
 * Method:    _createRenderTexture
 * Signature: (JLjava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_TextureManager__1createRenderTexture
  (JNIEnv *, jobject, jlong, jstring, jint, jint);

/*
 * Class:     vib_auxiliary_player_ogre_natives_TextureManager
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_TextureManager_delete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
