/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vib_auxiliary_player_ogre_natives_Texture */

#ifndef _Included_vib_auxiliary_player_ogre_natives_Texture
#define _Included_vib_auxiliary_player_ogre_natives_Texture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vib_auxiliary_player_ogre_natives_Texture
 * Method:    _getBuffer
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_vib_auxiliary_player_ogre_natives_Texture__1getBuffer
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     vib_auxiliary_player_ogre_natives_Texture
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vib_auxiliary_player_ogre_natives_Texture_delete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
