namespace animationparameters
{
    public enum BAPType
    {
        null_bap,
        sacroiliac_tilt, //1
        sacroiliac_torsion,
        sacroiliac_roll,
        l_hip_flexion,
        r_hip_flexion,
        l_hip_abduct,
        r_hip_abduct,
        l_hip_twisting,
        r_hip_twisting,
        l_knee_flexion, //10
        r_knee_flexion,
        l_knee_twisting,
        r_knee_twisting,
        l_ankle_flexion,
        r_ankle_flexion,
        l_ankle_twisting,
        r_ankle_twisting,
        l_subtalar_flexion,
        r_subtalar_flexion,
        l_midtarsal_twisting, //20
        r_midtarsal_twisting,
        l_metatarsal_flexion,
        r_metatarsal_flexion,
        l_sternoclavicular_abduct,
        r_sternoclavicular_abduct,
        l_sternoclavicular_rotate,
        r_sternoclavicular_rotate,
        l_acromioclavicular_abduct,
        r_acromioclavicular_abduct,
        l_acromioclavicular_rotate, //30
        r_acromioclavicular_rotate,
        l_shoulder_flexion,
        r_shoulder_flexion,
        l_shoulder_abduct,
        r_shoulder_abduct,
        l_shoulder_twisting,
        r_shoulder_twisting,
        l_elbow_flexion,
        r_elbow_flexion,
        l_elbow_twisting, //40
        r_elbow_twisting,
        l_wrist_flexion,
        r_wrist_flexion,
        l_wrist_pivot,
        r_wrist_pivot,
        l_wrist_twisting,
        r_wrist_twisting,
        skullbase_roll,
        skullbase_torsion,
        skullbase_tilt, // 50
        vc1_roll,
        vc1_torsion,
        vc1_tilt,
        vc2_roll,
        vc2_torsion,
        vc2_tilt,
        vc3_roll,
        vc3_torsion,
        vc3_tilt,
        vc4_roll, //60
        vc4_torsion,
        vc4_tilt,
        vc5_roll,
        vc5_torsion,
        vc5_tilt,
        vc6_roll,
        vc6_torsion,
        vc6_tilt,
        vc7_roll,
        vc7_torsion, //70
        vc7_tilt,
        vt1_roll,
        vt1_torsion,
        vt1_tilt,
        vt2_roll,
        vt2_torsion,
        vt2_tilt,
        vt3_roll,
        vt3_torsion,
        vt3_tilt, //80
        vt4_roll,
        vt4_torsion,
        vt4_tilt,
        vt5_roll,
        vt5_torsion,
        vt5_tilt,
        vt6_roll,
        vt6_torsion,
        vt6_tilt,
        vt7_roll, //90
        vt7_torsion,
        vt7_tilt,
        vt8_roll,
        vt8_torsion,
        vt8_tilt,
        vt9_roll,
        vt9_torsion,
        vt9_tilt,
        vt10_roll,
        vt10_torsion, //100
        vt10_tilt,
        vt11_roll,
        vt11_torsion,
        vt11_tilt,
        vt12_roll,
        vt12_torsion,
        vt12_tilt,
        vl1_roll,
        vl1_torsion,
        vl1_tilt, //110
        vl2_roll,
        vl2_torsion,
        vl2_tilt,
        vl3_roll,
        vl3_torsion,
        vl3_tilt,
        vl4_roll,
        vl4_torsion,
        vl4_tilt,
        vl5_roll, //120
        vl5_torsion,
        vl5_tilt,
        l_pinky0_flexion,
        r_pinky0_flexion,
        l_pinky1_flexion,
        r_pinky1_flexion,
        l_pinky1_pivot,
        r_pinky1_pivot,
        l_pinky1_twisting,
        r_pinky1_twisting, //130
        l_pinky2_flexion,
        r_pinky2_flexion,
        l_pinky3_flexion,
        r_pinky3_flexion,
        l_ring0_flexion,
        r_ring0_flexion,
        l_ring1_flexion,
        r_ring1_flexion,
        l_ring1_pivot,
        r_ring1_pivot, //140
        l_ring1_twisting,
        r_ring1_twisting,
        l_ring2_flexion,
        r_ring2_flexion,
        l_ring3_flexion,
        r_ring3_flexion,
        l_middle0_flexion,
        r_middle0_flexion,
        l_middle1_flexion,
        r_middle1_flexion, //150
        l_middle1_pivot,
        r_middle1_pivot,
        l_middle1_twisting,
        r_middle1_twisting,
        l_middle2_flexion,
        r_middle2_flexion,
        l_middle3_flexion,
        r_middle3_flexion,
        l_index0_flexion,
        r_index0_flexion,//160
        l_index1_flexion,
        r_index1_flexion,
        l_index1_pivot,
        r_index1_pivot,
        l_index1_twisting,
        r_index1_twisting,
        l_index2_flexion,
        r_index2_flexion,
        l_index3_flexion,
        r_index3_flexion, //170
        l_thumb1_flexion,
        r_thumb1_flexion,
        l_thumb1_pivot,
        r_thumb1_pivot,
        l_thumb1_twisting,
        r_thumb1_twisting,
        l_thumb2_flexion,
        r_thumb2_flexion,
        l_thumb3_flexion,
        r_thumb3_flexion, //180
        HumanoidRoot_tr_vertical,
        HumanoidRoot_tr_lateral,
        HumanoidRoot_tr_frontal,
        // global rotation
        HumanoidRoot_rt_body_turn,
        HumanoidRoot_rt_body_roll,
        HumanoidRoot_rt_body_tilt // 186
    }
}
